@BASE_URL = http://localhost:4000

# @name create_user
POST {{BASE_URL}}/people
Content-Type: application/json

{
    "document": "051.554.903-75",
    "password": "123456",
    "name": "Giselle"
}
###

@document = {{create_user.request.body.document}}
@password = {{create_user.request.body.password}}

# @name login
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "document": "{{document}}",
    "password": "{{password}}"
}
###
@token = {{login.response.body.token}}

# @name create_account
POST {{BASE_URL}}/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "branch": "001",
    "account": "1234567-1"
}
###

@accountId = {{create_account.response.body.id}}

GET {{BASE_URL}}/accounts
Authorization: Bearer {{token}}
###

POST {{BASE_URL}}/accounts/{{accountId}}/cards
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "virtual",
  "number": "1234 5678 9101 11213",
  "cvv": "456"
}
###

GET {{BASE_URL}}/accounts/{{accountId}}/cards
Authorization: Bearer {{token}}
###

GET {{BASE_URL}}/cards?itemsPerPage=10&currentPage=1
Authorization: Bearer {{token}}
###


# @name create_transaction
POST {{BASE_URL}}/accounts/{{accountId}}/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "value": 10,
  "description": "Para comprar o bolo."
}
###

@transactionId =  {{create_transaction.response.body.id}}

# @name create_transaction_internal
POST {{BASE_URL}}/accounts/{{accountId}}/transactions/internal
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "receiverAccountId": "e41e0e24-473b-4d22-bc40-babe2d5409f8",
    "value": 40.50,
    "description": "Para ajudar no aluguel"
}
###

@transactionInternalId =  {{create_transaction_internal.response.body.id}}

GET {{BASE_URL}}/accounts/{{accountId}}/transactions?itemsPerPage=10&currentPage=1&type=credit 
Authorization: Bearer {{token}}
###


GET {{BASE_URL}}/accounts/{{accountId}}/balance
Authorization: Bearer {{token}}
###

POST {{BASE_URL}}/accounts/{{accountId}}/transactions/{{transactionId}}/revert
Authorization: Bearer {{token}}
###


