version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cubos_bank
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: node:22-bullseye
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cubos_bank
    depends_on:
      - db
    command: sh -c "npm i && npm run prisma:setup && npm run start:prod"

volumes:
  pgdata:
